; boot.asm

[bits 32]

section .multiboot

	MULTIBOOT_PAGE_ALIGN     equ 0x00000001
	MULTIBOOT_MEMORY_INFO    equ 0x00000002
	MULTIBOOT_VIDEO_MODE     equ 0x00000004
	MULTIBOOT_ADDRESS_FIELDS equ 0x00010000

	MULTIBOOT_MAGIC            equ 0x1BADB002
	MULTIBOOT_FLAGS            equ MULTIBOOT_PAGE_ALIGN | MULTIBOOT_MEMORY_INFO
	MULTIBOOT_CHECKSUM         equ -(MULTIBOOT_MAGIC + MULTIBOOT_FLAGS)

	; make the multiboot aligned on 32-bits
	align 4
	dd MULTIBOOT_MAGIC
	dd MULTIBOOT_FLAGS
	dd MULTIBOOT_CHECKSUM
